### ISSUE TITLE
Failing to compile on Android RN 0.32

### ISSUE THREAD

**Issue by abbasfreestyle** [ldn0x7dc/react-native-media-kit#27]
Unfortunately i can't seem to get passed the compiling phase with this:

```
:react-native-media-kit:compileLint
:react-native-media-kit:copyReleaseLint UP-TO-DATE
:react-native-media-kit:preBuild UP-TO-DATE
:react-native-media-kit:preReleaseBuild UP-TO-DATE
:react-native-media-kit:checkReleaseManifest
:react-native-media-kit:preDebugAndroidTestBuild UP-TO-DATE
:react-native-media-kit:preDebugBuild UP-TO-DATE
:react-native-media-kit:preDebugUnitTestBuild UP-TO-DATE
:react-native-media-kit:preReleaseUnitTestBuild UP-TO-DATE
:react-native-media-kit:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-media-kit:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-media-kit:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-media-kit:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-media-kit:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-media-kit:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-media-kit:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-media-kit:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-media-kit:prepareComFacebookFrescoImagepipelineOkhttp30110LibraryUP-TO-DATE
:react-native-media-kit:prepareComFacebookReactReactNative0320Library UP-TO-DATE
:react-native-media-kit:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-media-kit:prepareComGoogleAndroidExoplayerExoplayerR156Library UP-TO-DATE
:react-native-media-kit:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-media-kit:prepareReleaseDependencies
:react-native-media-kit:compileReleaseAidl UP-TO-DATE
:react-native-media-kit:compileReleaseRenderscript UP-TO-DATE
:react-native-media-kit:generateReleaseBuildConfig UP-TO-DATE
:react-native-media-kit:generateReleaseAssets UP-TO-DATE
:react-native-media-kit:mergeReleaseAssets UP-TO-DATE
:react-native-media-kit:generateReleaseResValues UP-TO-DATE
:react-native-media-kit:generateReleaseResources UP-TO-DATE
:react-native-media-kit:mergeReleaseResources UP-TO-DATE
:react-native-media-kit:processReleaseManifest UP-TO-DATE
:react-native-media-kit:processReleaseResources UP-TO-DATE
:react-native-media-kit:generateReleaseSources UP-TO-DATE
:react-native-media-kit:processReleaseJavaRes UP-TO-DATE
:react-native-media-kit:compileReleaseJavaWithJavac
/Users/mycomp/Apps/reactApp/node_modules/react-native-media-kit/android/src/main/java/com/greatdroid/reactnative/media/player/ReactMediaPlayerViewManager.java:95: error: no suitable constructor found for Event(int,long)
                .dispatchEvent(new Event(view.getId(), SystemClock.uptimeMillis()) {
                               ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
/Users/mycomp/Apps/reactApp/node_modules/react-native-media-kit/android/src/main/java/com/greatdroid/reactnative/media/player/ReactMediaPlayerViewManager.java:111: error: no suitable constructor found for Event(int,long)
                .dispatchEvent(new Event(view.getId(), SystemClock.uptimeMillis()) {
                               ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
/Users/mycomp/Apps/reactApp/node_modules/react-native-media-kit/android/src/main/java/com/greatdroid/reactnative/media/player/ReactMediaPlayerViewManager.java:127: error: no suitable constructor found for Event(int,long)
                .dispatchEvent(new Event(view.getId(), SystemClock.uptimeMillis()) {
                               ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
/Users/mycomp/Apps/reactApp/node_modules/react-native-media-kit/android/src/main/java/com/greatdroid/reactnative/media/player/ReactMediaPlayerViewManager.java:143: error: no suitable constructor found for Event(int,long)
                .dispatchEvent(new Event(view.getId(), SystemClock.uptimeMillis()) {
                               ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
/Users/mycomp/Apps/reactApp/node_modules/react-native-media-kit/android/src/main/java/com/greatdroid/reactnative/media/player/ReactMediaPlayerViewManager.java:159: error: no suitable constructor found for Event(int,long)
                .dispatchEvent(new Event(view.getId(), SystemClock.uptimeMillis()) {
                               ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
/Users/mycomp/Apps/reactApp/node_modules/react-native-media-kit/android/src/main/java/com/greatdroid/reactnative/media/player/ReactMediaPlayerViewManager.java:175: error: no suitable constructor found for Event(int,long)
                .dispatchEvent(new Event(view.getId(), SystemClock.uptimeMillis()) {
                               ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
/Users/mycomp/Apps/reactApp/node_modules/react-native-media-kit/android/src/main/java/com/greatdroid/reactnative/media/player/ReactMediaPlayerViewManager.java:193: error: no suitable constructor found for Event(int,long)
                  .dispatchEvent(new Event(view.getId(), SystemClock.uptimeMillis()) {
                                 ^
    constructor Event.Event() is not applicable
      (actual and formal argument lists differ in length)
    constructor Event.Event(int) is not applicable
      (actual and formal argument lists differ in length)
7 errors
:react-native-media-kit:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

What seems to be the problem?

Many thanks

**Comment by abbasfreestyle** [comment]
It seems that it can't find com.facebook.react.uimanager.event anymore.

**Comment by polacekpavel** [comment]
@abbasfreestyle Can you try this [pull](https://github.com/ldn0x7dc/react-native-media-kit/pull/30) ? 

`npm install https://github.com/ldn0x7dc/react-native-media-kit#pull/30/head --save`

**Comment by abbasfreestyle** [comment]
@polacekpavel Thank you.

It's installed and built successfully.

But now there's a problem when pressing play button. I get the error:

```
undefined is not an object (evaluating 'UIManager.RCTMediaPlayerView.Commands')
play
    MediaPlayerView.js:151
onPauseOrPlay
    MediaPlayerView.js:100
touchableHandlePress
    TouchableOpacity.js:119
_performSideEffectsForTransition
    Touchable.js:715
_receiveSignal
    Touchable.js:631
touchableHandleResponderRelease
    Touchable.js:405
invokeGuardedCallback
    ReactErrorUtils.js:26
executeDispatch
    EventPluginUtils.js:89
executeDispatchesInOrder
    EventPluginUtils.js:112
executeDispatchesAndRelease
    EventPluginHub.js:44
executeDispatchesAndReleaseTopLevel
    EventPluginHub.js:55
forEachAccumulated
    forEachAccumulated.js:25
processEventQueue
    EventPluginHub.js:231
runEventQueueInBatch
    ReactEventEmitterMixin.js:18
handleTopLevel
    ReactEventEmitterMixin.js:29
<unknown>
    ReactNativeEventEmitter.js:125
perform
    Transaction.js:138
batchedUpdates
    ReactDefaultBatchingStrategy.js:63
batchedUpdates
    ReactUpdates.js:98
_receiveRootNodeIDEvent
    ReactNativeEventEmitter.js:124
receiveTouches
    ReactNativeEventEmitter.js:186
__callFunction
    MessageQueue.js:229
<unknown>
    MessageQueue.js:111
guard
    MessageQueue.js:42
callFunctionReturnFlushedQueue
    MessageQueue.js:110

```

I've tested the original kit on RN 0.30 and it installs and plays the video fine using the same code. for e.g:

`npm install --save react-native-media-kit@latest`

```
const {height,width} = Dimensions.get('window');

import {Video} from 'react-native-media-kit';

render() {
  return (
    <Video
      style={{width: width, height: width / (16/9)}}
      src={'http://v.yoai.com/femme_tampon_tutorial.mp4'}
      autoplay={false}
      preload={'none'}
      loop={false}
      controls={true}
      muted={false}
      poster={'http://static.yoaicdn.com/shoppc/images/cover_img_e1e9e6b.jpg'}
    />
  );
}
```

**Comment by shashilo** [comment]
Same issue for me. After adding pull/30, compiles but play just spins.

**Comment by muvv** [comment]
same iisue for me also,it just spins,but video never plays. pls fix this issue

**Comment by acresta88** [comment]
Same issue for me, I tried to install react-native 36 and it broke everything on Android, but it seems fine on iOS.

**Comment by emisty** [comment]
Same issue for me
rn 35.0
undefined is not an object (evaluating 'UIManager.RCTMediaPlayerView.Commands')

**Comment by emisty** [comment]
@polacekpavel  help me!
E:\androidapp\snowflake>npm install https://github.com/ldn0x7dc/react-native-media-kit#pull/30/head --save
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  git+https://github.com/ldn0x7dc/react-native-media-kit.git#pull/30/head resetting remote C:\Users\jzbis\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ldn0x7dc-react-native-media-kit-git-pull-30-head-ad6d963f because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
